package defpackage;

import android.content.pm.ApplicationInfo;
import android.content.pm.PackageInfo;
import android.os.Bundle;
import android.os.Parcel;
import android.os.Parcelable;
import com.google.android.gms.ads.internal.client.zzeh;
import com.google.android.gms.ads.internal.client.zzm;
import com.google.android.gms.ads.internal.client.zzr;
import com.google.android.gms.ads.internal.util.client.VersionInfoParcel;
import com.google.android.gms.common.internal.safeparcel.AbstractSafeParcelable;
import com.google.android.gms.internal.ads.zzbkh;
import com.google.android.gms.internal.ads.zzbqs;
import com.google.android.gms.internal.ads.zzbza;
import java.util.DesugarCollections;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/* JADX INFO: compiled from: r8-map-id-6bfc5c3105a4be2b3e0ed36dbd4f8244cea9222f352ced40fd941a9b8aa981c8 */
/* JADX INFO: loaded from: classes.dex */
public final class a92 extends AbstractSafeParcelable {
    public static final Parcelable.Creator<a92> CREATOR = new zzbza();
    public final long A;
    public final String B;
    public final float C;
    public final int D;
    public final int E;
    public final boolean F;
    public final String G;
    public final boolean H;
    public final String I;
    public final boolean J;
    public final int K;
    public final Bundle L;
    public final String M;
    public final zzeh N;
    public final boolean O;
    public final Bundle P;
    public final String Q;
    public final String R;
    public final String S;
    public final boolean T;
    public final List U;
    public final String V;
    public final List W;
    public final int X;
    public final boolean Y;
    public final boolean Z;
    public final int a;
    public final boolean a0;
    public final Bundle b;
    public final ArrayList b0;
    public final zzm c;
    public final String c0;
    public final zzr d;
    public final zzbqs d0;
    public final String e;
    public final String e0;
    public final ApplicationInfo f;
    public final Bundle f0;
    public final PackageInfo g;
    public final String h;
    public final String i;
    public final String j;
    public final VersionInfoParcel k;
    public final Bundle l;
    public final int m;
    public final List n;
    public final Bundle o;
    public final boolean p;
    public final int q;
    public final int r;
    public final float s;
    public final String t;
    public final long u;
    public final String v;
    public final List w;
    public final String x;
    public final zzbkh y;
    public final List z;

    public a92(int i, Bundle bundle, zzm zzmVar, zzr zzrVar, String str, ApplicationInfo applicationInfo, PackageInfo packageInfo, String str2, String str3, String str4, VersionInfoParcel versionInfoParcel, Bundle bundle2, int i2, ArrayList arrayList, Bundle bundle3, boolean z, int i3, int i4, float f, String str5, long j, String str6, ArrayList arrayList2, String str7, zzbkh zzbkhVar, ArrayList arrayList3, long j2, String str8, float f2, boolean z2, int i5, int i6, boolean z3, String str9, String str10, boolean z4, int i7, Bundle bundle4, String str11, zzeh zzehVar, boolean z5, Bundle bundle5, String str12, String str13, String str14, boolean z6, ArrayList arrayList4, String str15, ArrayList arrayList5, int i8, boolean z7, boolean z8, boolean z9, ArrayList arrayList6, String str16, zzbqs zzbqsVar, String str17, Bundle bundle6) {
        this.a = i;
        this.b = bundle;
        this.c = zzmVar;
        this.d = zzrVar;
        this.e = str;
        this.f = applicationInfo;
        this.g = packageInfo;
        this.h = str2;
        this.i = str3;
        this.j = str4;
        this.k = versionInfoParcel;
        this.l = bundle2;
        this.m = i2;
        this.n = arrayList;
        this.z = arrayList3 == null ? Collections.EMPTY_LIST : DesugarCollections.unmodifiableList(arrayList3);
        this.o = bundle3;
        this.p = z;
        this.q = i3;
        this.r = i4;
        this.s = f;
        this.t = str5;
        this.u = j;
        this.v = str6;
        this.w = arrayList2 == null ? Collections.EMPTY_LIST : DesugarCollections.unmodifiableList(arrayList2);
        this.x = str7;
        this.y = zzbkhVar;
        this.A = j2;
        this.B = str8;
        this.C = f2;
        this.H = z2;
        this.D = i5;
        this.E = i6;
        this.F = z3;
        this.G = str9;
        this.I = str10;
        this.J = z4;
        this.K = i7;
        this.L = bundle4;
        this.M = str11;
        this.N = zzehVar;
        this.O = z5;
        this.P = bundle5;
        this.Q = str12;
        this.R = str13;
        this.S = str14;
        this.T = z6;
        this.U = arrayList4;
        this.V = str15;
        this.W = arrayList5;
        this.X = i8;
        this.Y = z7;
        this.Z = z8;
        this.a0 = z9;
        this.b0 = arrayList6;
        this.c0 = str16;
        this.d0 = zzbqsVar;
        this.e0 = str17;
        this.f0 = bundle6;
    }

    @Override // android.os.Parcelable
    public final void writeToParcel(Parcel parcel, int i) {
        int iV = n8.V(20293, parcel);
        n8.P(parcel, 1, 4);
        parcel.writeInt(this.a);
        n8.A(parcel, 2, this.b);
        n8.F(parcel, 3, this.c, i);
        n8.F(parcel, 4, this.d, i);
        n8.G(parcel, 5, this.e);
        n8.F(parcel, 6, this.f, i);
        n8.F(parcel, 7, this.g, i);
        n8.G(parcel, 8, this.h);
        n8.G(parcel, 9, this.i);
        n8.G(parcel, 10, this.j);
        n8.F(parcel, 11, this.k, i);
        n8.A(parcel, 12, this.l);
        n8.P(parcel, 13, 4);
        parcel.writeInt(this.m);
        n8.I(parcel, 14, this.n);
        n8.A(parcel, 15, this.o);
        n8.P(parcel, 16, 4);
        parcel.writeInt(this.p ? 1 : 0);
        n8.P(parcel, 18, 4);
        parcel.writeInt(this.q);
        n8.P(parcel, 19, 4);
        parcel.writeInt(this.r);
        n8.P(parcel, 20, 4);
        parcel.writeFloat(this.s);
        n8.G(parcel, 21, this.t);
        n8.P(parcel, 25, 8);
        parcel.writeLong(this.u);
        n8.G(parcel, 26, this.v);
        n8.I(parcel, 27, this.w);
        n8.G(parcel, 28, this.x);
        n8.F(parcel, 29, this.y, i);
        n8.I(parcel, 30, this.z);
        n8.P(parcel, 31, 8);
        parcel.writeLong(this.A);
        n8.G(parcel, 33, this.B);
        n8.P(parcel, 34, 4);
        parcel.writeFloat(this.C);
        n8.P(parcel, 35, 4);
        parcel.writeInt(this.D);
        n8.P(parcel, 36, 4);
        parcel.writeInt(this.E);
        n8.P(parcel, 37, 4);
        parcel.writeInt(this.F ? 1 : 0);
        n8.G(parcel, 39, this.G);
        n8.P(parcel, 40, 4);
        parcel.writeInt(this.H ? 1 : 0);
        n8.G(parcel, 41, this.I);
        n8.P(parcel, 42, 4);
        parcel.writeInt(this.J ? 1 : 0);
        n8.P(parcel, 43, 4);
        parcel.writeInt(this.K);
        n8.A(parcel, 44, this.L);
        n8.G(parcel, 45, this.M);
        n8.F(parcel, 46, this.N, i);
        n8.P(parcel, 47, 4);
        parcel.writeInt(this.O ? 1 : 0);
        n8.A(parcel, 48, this.P);
        n8.G(parcel, 49, this.Q);
        n8.G(parcel, 50, this.R);
        n8.G(parcel, 51, this.S);
        n8.P(parcel, 52, 4);
        parcel.writeInt(this.T ? 1 : 0);
        n8.D(parcel, 53, this.U);
        n8.G(parcel, 54, this.V);
        n8.I(parcel, 55, this.W);
        n8.P(parcel, 56, 4);
        parcel.writeInt(this.X);
        n8.P(parcel, 57, 4);
        parcel.writeInt(this.Y ? 1 : 0);
        n8.P(parcel, 58, 4);
        parcel.writeInt(this.Z ? 1 : 0);
        n8.P(parcel, 59, 4);
        parcel.writeInt(this.a0 ? 1 : 0);
        n8.I(parcel, 60, this.b0);
        n8.G(parcel, 61, this.c0);
        n8.F(parcel, 63, this.d0, i);
        n8.G(parcel, 64, this.e0);
        n8.A(parcel, 65, this.f0);
        n8.e0(iV, parcel);
    }
}
