package defpackage;

import android.content.Context;
import com.google.android.gms.internal.ads.g3;
import com.google.android.gms.internal.ads.o3;
import com.google.android.gms.internal.ads.p3;
import com.google.android.gms.internal.ads.zzcdu;
import com.google.android.gms.internal.ads.zzcjl;
import com.google.android.gms.internal.ads.zzcti;
import com.google.android.gms.internal.ads.zzctj;
import com.google.android.gms.internal.ads.zzctp;
import com.google.android.gms.internal.ads.zzcwe;
import com.google.android.gms.internal.ads.zzcwv;
import com.google.android.gms.internal.ads.zzcyn;
import com.google.android.gms.internal.ads.zzcys;
import com.google.android.gms.internal.ads.zzday;
import com.google.android.gms.internal.ads.zzdba;
import com.google.android.gms.internal.ads.zzdbs;
import com.google.android.gms.internal.ads.zzdbx;
import com.google.android.gms.internal.ads.zzdce;
import com.google.android.gms.internal.ads.zzdcr;
import com.google.android.gms.internal.ads.zzdfw;
import com.google.android.gms.internal.ads.zzdiq;
import com.google.android.gms.internal.ads.zzdje;
import com.google.android.gms.internal.ads.zzdkr;
import com.google.android.gms.internal.ads.zzdlr;
import com.google.android.gms.internal.ads.zzdmc;
import com.google.android.gms.internal.ads.zzdmh;
import com.google.android.gms.internal.ads.zzduu;
import com.google.android.gms.internal.ads.zzdxz;
import com.google.android.gms.internal.ads.zzekl;
import com.google.android.gms.internal.ads.zzfer;
import com.google.android.gms.internal.ads.zzfjc;
import com.google.android.gms.internal.ads.zzfmk;
import com.google.android.gms.internal.ads.zzguo;
import com.google.android.gms.internal.ads.zzgup;
import com.google.android.gms.internal.ads.zzikg;
import com.google.android.gms.internal.ads.zzikp;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Set;

/* JADX INFO: compiled from: r8-map-id-6bfc5c3105a4be2b3e0ed36dbd4f8244cea9222f352ced40fd941a9b8aa981c8 */
/* JADX INFO: loaded from: classes.dex */
public final class hd2 extends zzcti {
    public final zzcwv a;
    public final zzdkr b;
    public final zzctj c;
    public final gd2 d;
    public final jd2 e;
    public final se3 f;
    public final se3 g;
    public final se3 h;
    public final se3 i;
    public final se3 j;
    public final se3 k;
    public final se3 l;
    public final se3 m;
    public final se3 n;
    public final se3 o;
    public final se3 p;
    public final se3 q;
    public final se3 r;
    public final se3 s;
    public final se3 t;
    public final se3 u;
    public final se3 v;
    public final se3 w;
    public final se3 x;

    public hd2(gd2 gd2Var, jd2 jd2Var, zzcwv zzcwvVar, zzdkr zzdkrVar, zzctj zzctjVar) {
        this.d = gd2Var;
        this.e = jd2Var;
        new zzcys();
        this.a = zzcwvVar;
        this.b = zzdkrVar;
        this.c = zzctjVar;
        new zzcyn();
        new zzdba();
        int i = 0;
        ng2 ng2Var = new ng2(zzcwvVar, i);
        se3 se3Var = jd2Var.i;
        qc2 qc2Var = gd2Var.H0;
        se3 se3VarA = se3.a(new p3(se3Var, ng2Var));
        se3 se3VarA2 = se3.a(new o3(se3VarA, i));
        se3 se3VarA3 = se3.a(new ee2(gd2Var.I0, 9));
        se3 se3VarA4 = se3.a(new lf2(ng2Var, i));
        yc2 yc2Var = gd2Var.j;
        zzctp zzctpVar = nf2.a;
        se3 se3VarA5 = se3.a(new w32(yc2Var, se3VarA4, zzctpVar, 1));
        sc2 sc2Var = gd2Var.h;
        se3 se3VarA6 = se3.a(new gf2(sc2Var, se3VarA5, i));
        int i2 = ou2.a;
        se3 se3VarA7 = se3.a(new jf2(se3VarA3, se3VarA6, gd2Var.d, se3.a(new ic2(se3VarA5, se3VarA3, 3)), gd2Var.g));
        zzfmk zzfmkVar = pu2.a;
        se3 se3VarA8 = se3.a(new ic2(se3VarA7, se3VarA4, 5));
        int i3 = we3.c;
        ArrayList arrayList = new ArrayList(1);
        ArrayList arrayList2 = new ArrayList(3);
        arrayList2.add(jd2Var.q);
        arrayList2.add(jd2Var.r);
        arrayList.add(se3VarA2);
        arrayList2.add(se3VarA8);
        se3 se3VarA9 = se3.a(new th2(new we3(arrayList, arrayList2), 3));
        this.f = se3VarA9;
        se3 se3VarA10 = se3.a(di2.a);
        this.g = se3VarA10;
        se3 se3Var2 = gd2Var.d;
        se3 se3VarA11 = se3.a(new gf2(se3VarA10, (zzikp) se3Var2, 4));
        ng2 ng2Var2 = new ng2(zzcwvVar, 3);
        ng2 ng2Var3 = new ng2(zzcwvVar, 2);
        sc2 sc2Var2 = gd2Var.h;
        se3 se3VarA12 = se3.a(new ee2(sc2Var2, 20));
        se3 se3VarA13 = se3.a(kl2.a);
        se3 se3VarA14 = se3.a(new we2(sc2Var2, gd2Var.E, se3VarA12, se3VarA13, gd2Var.F0, gd2Var.e));
        se3 se3VarA15 = se3.a(new we2(gd2Var.M, gd2Var.L, ng2Var, ng2Var3, se3VarA14, jd2Var.f));
        yi2 yi2Var = new yi2(zzdkrVar, 1);
        yi2 yi2Var2 = new yi2(zzdkrVar, 2);
        se3 se3VarA16 = se3.a(new gf2(se3VarA10, (zzikp) se3Var2, 9));
        ArrayList arrayList3 = new ArrayList(1);
        ArrayList arrayList4 = new ArrayList(1);
        arrayList4.add(jd2Var.w);
        arrayList3.add(se3VarA16);
        se3 se3VarA17 = se3.a(new ha2(new we3(arrayList3, arrayList4), ng2Var, ng2Var2, 5));
        se3 se3VarA18 = se3.a(new pe2(ng2Var2, 8));
        this.h = se3VarA18;
        sc2 sc2Var3 = gd2Var.h;
        se3 se3Var3 = gd2Var.d;
        se3 se3VarA19 = se3.a(new ef2(sc2Var3, se3Var3, gd2Var.e, ng2Var2, ng2Var, jd2Var.n, se3VarA15, yi2Var, yi2Var2, gd2Var.I, jd2Var.o, jd2Var.f, jd2Var.v, se3VarA17, se3VarA18, jd2Var.l));
        uc2 uc2Var = new uc2(se3VarA19, 24);
        yg2 yg2Var = new yg2(se3.a(new ye2(ng2Var, gd2Var.Y, 0)), 9);
        se3 se3Var4 = gd2Var.E0;
        se3 se3Var5 = gd2Var.l;
        se3 se3VarA20 = se3.a(new zg2(sc2Var3, se3Var4, se3Var5, ng2Var2, ng2Var, gd2Var.K, zzctpVar));
        int i4 = 6;
        se3 se3VarA21 = se3.a(new yg2(se3VarA20, i4));
        se3 se3VarA22 = se3.a(new gf2(se3VarA10, (zzikp) se3Var3, i4));
        uc2 uc2Var2 = new uc2(se3VarA17, 12);
        uc2 uc2Var3 = new uc2(se3VarA19, 26);
        se3 se3VarA23 = se3.a(new ic2(se3VarA7, se3VarA4, 4));
        yc2 yc2Var2 = gd2Var.j;
        se3 se3VarA24 = se3.a(new fg2(sc2Var3, yc2Var2, ng2Var, yi2Var2, se3Var5));
        this.i = se3VarA24;
        se3 se3VarA25 = se3.a(new fg2(sc2Var3, (zzikg) yi2Var2, ng2Var, yc2Var2, se3VarA24, 4));
        yg2 yg2Var2 = new yg2(se3VarA25, 17);
        ArrayList arrayList5 = new ArrayList(7);
        ArrayList arrayList6 = new ArrayList(3);
        arrayList5.add(jd2Var.x);
        arrayList5.add(jd2Var.y);
        arrayList6.add(jd2Var.z);
        arrayList6.add(jd2Var.A);
        arrayList5.add(se3VarA21);
        arrayList5.add(se3VarA22);
        arrayList5.add(uc2Var2);
        arrayList5.add(uc2Var3);
        arrayList6.add(se3VarA23);
        arrayList5.add(yg2Var2);
        int i5 = 2;
        se3 se3VarA26 = se3.a(new th2(new we3(arrayList5, arrayList6), i5));
        this.j = se3VarA26;
        ng2 ng2Var4 = new ng2(zzcwvVar, 1);
        se3 se3VarA27 = se3.a(new yg2(se3VarA20, i5));
        uc2 uc2Var4 = new uc2(se3VarA19, 28);
        ArrayList arrayList7 = new ArrayList(2);
        ArrayList arrayList8 = new ArrayList(1);
        arrayList8.add(jd2Var.B);
        arrayList7.add(se3VarA27);
        arrayList7.add(uc2Var4);
        se3 se3VarA28 = se3.a(new fg2(se3VarA26, ng2Var, gd2Var.e, ng2Var4, se3.a(new th2(new we3(arrayList7, arrayList8), 10))));
        this.k = se3VarA28;
        la2 la2Var = new la2(zzdkrVar, se3VarA28, 12);
        sc2 sc2Var4 = gd2Var.h;
        rh2 rh2Var = jd2Var.e;
        se3 se3VarA29 = se3.a(new we2(new yf2(sc2Var4, rh2Var, 2), sc2Var4, gd2Var.x, new yi2(zzdkrVar, 0), mf2.a, ng2Var));
        this.l = se3VarA29;
        yg2 yg2Var3 = new yg2(se3VarA29, 23);
        ArrayList arrayList9 = new ArrayList(5);
        ArrayList arrayList10 = new ArrayList(3);
        arrayList9.add(jd2Var.s);
        arrayList10.add(jd2Var.t);
        arrayList10.add(jd2Var.u);
        arrayList9.add(se3VarA11);
        arrayList9.add(uc2Var);
        arrayList9.add(yg2Var);
        arrayList10.add(la2Var);
        arrayList9.add(yg2Var3);
        se3 se3VarA30 = se3.a(new th2(new we3(arrayList9, arrayList10), 4));
        this.m = se3VarA30;
        se3 se3VarA31 = se3.a(new yg2(se3VarA20, 5));
        se3 se3VarA32 = se3.a(new gf2(se3VarA10, (zzikp) se3Var2, 3));
        se3 se3VarA33 = se3.a(new yg2(se3.a(new yf2(gd2Var.A0, rh2Var, 1)), 3));
        uc2 uc2Var5 = new uc2(se3VarA19, 23);
        se3 se3VarA34 = se3.a(new la2(gd2Var.U, ng2Var3, 11));
        yg2 yg2Var4 = new yg2(se3VarA34, 15);
        ArrayList arrayList11 = new ArrayList(6);
        ArrayList arrayList12 = new ArrayList(3);
        arrayList11.add(jd2Var.C);
        arrayList11.add(jd2Var.D);
        arrayList12.add(jd2Var.E);
        arrayList12.add(jd2Var.F);
        arrayList11.add(se3VarA31);
        arrayList11.add(se3VarA32);
        arrayList12.add(se3VarA33);
        arrayList11.add(uc2Var5);
        arrayList11.add(yg2Var4);
        se3 se3VarA35 = se3.a(new th2(new we3(arrayList11, arrayList12), 0));
        this.n = se3VarA35;
        uc2 uc2Var6 = new uc2(se3VarA19, 29);
        ArrayList arrayList13 = new ArrayList(1);
        ArrayList arrayList14 = new ArrayList(1);
        arrayList14.add(jd2Var.G);
        arrayList13.add(uc2Var6);
        this.o = se3.a(new th2(new we3(arrayList13, arrayList14), 19));
        int i6 = 1;
        uc2 uc2Var7 = new uc2(se3.a(new ye2(ng2Var, gd2Var.M, i6)), 22);
        ArrayList arrayList15 = new ArrayList(1);
        new ArrayList(1).add(jd2Var.H);
        arrayList15.add(uc2Var7);
        se3 se3VarA36 = se3.a(new gf2(se3VarA10, (zzikp) se3Var2, 10));
        ArrayList arrayList16 = new ArrayList(1);
        ArrayList arrayList17 = new ArrayList(1);
        arrayList17.add(jd2Var.I);
        arrayList16.add(se3VarA36);
        se3 se3VarA37 = se3.a(new th2(new we3(arrayList16, arrayList17), 20));
        this.p = se3VarA37;
        se3 se3VarA38 = se3.a(new o3(se3VarA, i6));
        uc2 uc2Var8 = new uc2(se3VarA19, 27);
        yg2 yg2Var5 = new yg2(se3VarA25, 18);
        se3 se3Var6 = jd2Var.i;
        xf2 xf2Var = new xf2(se3Var6, yc2Var, ng2Var, rh2Var);
        ArrayList arrayList18 = new ArrayList(9);
        ArrayList arrayList19 = new ArrayList(4);
        arrayList18.add(jd2Var.J);
        arrayList19.add(jd2Var.K);
        arrayList18.add(jd2Var.L);
        arrayList18.add(jd2Var.M);
        arrayList19.add(jd2Var.N);
        arrayList19.add(jd2Var.O);
        arrayList19.add(jd2Var.P);
        arrayList18.add(jd2Var.Q);
        arrayList18.add(jd2Var.R);
        arrayList18.add(se3VarA38);
        arrayList18.add(uc2Var8);
        arrayList18.add(yg2Var5);
        arrayList18.add(xf2Var);
        this.q = se3.a(new th2(new we3(arrayList18, arrayList19), 5));
        yg2 yg2Var6 = new yg2(se3.a(new uc2(se3VarA30, 11)), 1);
        se3 se3VarA39 = se3.a(new gf2(se3VarA10, (zzikp) se3Var2, 8));
        yg2 yg2Var7 = new yg2(se3VarA25, 19);
        yg2 yg2Var8 = new yg2(se3VarA34, 16);
        se3 se3VarA40 = se3.a(new fg2(ng2Var2, ng2Var, gd2Var.g, gd2Var.l, gd2Var.e));
        yg2 yg2Var9 = new yg2(se3VarA40, 22);
        ArrayList arrayList20 = new ArrayList(5);
        ArrayList arrayList21 = new ArrayList(1);
        arrayList21.add(jd2Var.T);
        arrayList20.add(yg2Var6);
        arrayList20.add(se3VarA39);
        arrayList20.add(yg2Var7);
        arrayList20.add(yg2Var8);
        arrayList20.add(yg2Var9);
        se3 se3VarA41 = se3.a(new th2(new we3(arrayList20, arrayList21), 9));
        this.r = se3VarA41;
        List list = Collections.EMPTY_LIST;
        ArrayList arrayList22 = new ArrayList(1);
        arrayList22.add(jd2Var.U);
        this.s = se3.a(new vi2(new we3(list, arrayList22)));
        se3 se3VarA42 = se3.a(new yg2(se3VarA20, 4));
        yg2 yg2Var10 = new yg2(se3VarA28, 14);
        ArrayList arrayList23 = new ArrayList(1);
        ArrayList arrayList24 = new ArrayList(1);
        arrayList23.add(se3VarA42);
        arrayList24.add(yg2Var10);
        we3 we3Var = new we3(arrayList23, arrayList24);
        int i7 = 13;
        this.t = se3.a(new th2(we3Var, i7));
        se3 se3VarA43 = se3.a(new gf2(se3VarA10, (zzikp) se3Var2, 5));
        uc2 uc2Var9 = new uc2(se3VarA19, 25);
        yg2 yg2Var11 = new yg2(se3VarA28, 11);
        se3 se3VarA44 = se3.a(new yf2(sc2Var, jd2Var.f, i7));
        this.u = se3VarA44;
        yg2 yg2Var12 = new yg2(se3VarA44, 12);
        ArrayList arrayList25 = new ArrayList(3);
        ArrayList arrayList26 = new ArrayList(2);
        arrayList26.add(jd2Var.V);
        arrayList25.add(se3VarA43);
        arrayList25.add(uc2Var9);
        arrayList26.add(yg2Var11);
        arrayList25.add(yg2Var12);
        th2 th2Var = new th2(new we3(arrayList25, arrayList26), 1);
        se3 se3VarA45 = se3.a(new yg2(se3VarA20, 0));
        ArrayList arrayList27 = new ArrayList(1);
        List list2 = Collections.EMPTY_LIST;
        arrayList27.add(se3VarA45);
        this.v = se3.a(new ha2(th2Var, new we3(arrayList27, list2), gd2Var.e, 4));
        se3 se3VarA46 = se3.a(new ic2(se3VarA7, se3VarA4, 6));
        yg2 yg2Var13 = new yg2(se3VarA28, 21);
        List list3 = Collections.EMPTY_LIST;
        ArrayList arrayList28 = new ArrayList(3);
        arrayList28.add(jd2Var.X);
        arrayList28.add(se3VarA46);
        arrayList28.add(yg2Var13);
        se3 se3VarA47 = se3.a(new ha2(se3Var6, new we3(list3, arrayList28), ng2Var, 6));
        se3 se3VarA48 = se3.a(new ha2(se3Var6, yc2Var, ng2Var, 3));
        se3 se3VarA49 = se3.a(new gf2((zzikp) se3Var6, se3VarA48, 2));
        la2 la2Var2 = new la2(zzdkrVar, se3Var2, 13);
        ArrayList arrayList29 = new ArrayList(1);
        ArrayList arrayList30 = new ArrayList(1);
        arrayList30.add(jd2Var.Y);
        arrayList29.add(la2Var2);
        this.w = se3.a(new il2(se3VarA35, se3VarA30, jd2Var.W, se3VarA41, jd2Var.S, gd2Var.d, se3VarA47, se3VarA7, se3VarA49, se3VarA48, gd2Var.I, se3.a(new th2(new we3(arrayList29, arrayList30), 12)), gd2Var.K, gd2Var.M, gd2Var.l, se3VarA37, se3VarA14, se3VarA13, gd2Var.p0, se3VarA40, se3VarA18));
        yg2 yg2Var14 = new yg2(se3.a(new yg2(se3VarA9, 26)), 24);
        yg2 yg2Var15 = new yg2(se3VarA44, 13);
        ArrayList arrayList31 = new ArrayList(1);
        ArrayList arrayList32 = new ArrayList(1);
        arrayList32.add(yg2Var14);
        arrayList31.add(yg2Var15);
        this.x = se3.a(new ic2(se3VarA41, se3.a(new th2(new we3(arrayList31, arrayList32), 18)), 8));
    }

    @Override // com.google.android.gms.internal.ads.zzcwg
    public final zzdbx b() {
        return (zzdbx) this.j.zzb();
    }

    @Override // com.google.android.gms.internal.ads.zzcti
    public final pf2 d() {
        zzcwv zzcwvVar = this.a;
        zzfjc zzfjcVar = zzcwvVar.a;
        k02.J(zzfjcVar);
        tt2 tt2Var = zzcwvVar.b;
        k02.J(tt2Var);
        zzdce zzdceVar = (zzdce) this.f.zzb();
        zzdcr zzdcrVar = (zzdcr) this.q.zzb();
        jd2 jd2Var = this.e;
        zzfer zzferVar = jd2Var.b.o;
        zzday zzdayVar = new zzday(tt2Var, zzcwvVar.c, (zzekl) jd2Var.k.zzb(), zzcwvVar.a(), (String) jd2Var.g.zzb());
        zzdfw zzdfwVar = (zzdfw) this.g.zzb();
        ji2 ji2Var = jd2Var.b;
        zzguo zzguoVarZzs = zzgup.zzs(2);
        zzguoVarZzs.g(ji2Var.g);
        bn2 bn2Var = (bn2) jd2Var.h.zzb();
        ta2 ta2Var = g3.a;
        k02.J(ta2Var);
        zzguoVarZzs.f(new zzdje(bn2Var, ta2Var));
        xh2 xh2Var = new xh2(zzguoVarZzs.h());
        qi2 qi2Var = (qi2) this.o.zzb();
        dh2 dh2Var = (dh2) this.h.zzb();
        gd2 gd2Var = this.d;
        zzcwe zzcweVar = new zzcwe(zzfjcVar, tt2Var, zzdceVar, zzdcrVar, zzferVar, zzdayVar, zzdfwVar, xh2Var, qi2Var, dh2Var, (jm2) gd2Var.p0.zzb());
        Context context = (Context) jd2Var.i.zzb();
        zzdkr zzdkrVar = this.b;
        zzcjl zzcjlVar = zzdkrVar.b;
        int i = this.c.a;
        se3 se3Var = gd2Var.l;
        zzdxz zzdxzVar = (zzdxz) se3Var.zzb();
        zzfjc zzfjcVar2 = zzcwvVar.a;
        k02.J(zzfjcVar2);
        i31 i31Var = new i31((Object) zzdxzVar, 19, (Object) zzfjcVar2, false);
        zzdmc zzdmcVar = zzdkrVar.a;
        zzguo zzguoVarZzs2 = zzgup.zzs(3);
        Set setB = zzdkrVar.b((ch2) this.k.zzb());
        k02.J(setB);
        zzguoVarZzs2.g(setB);
        zzdmh zzdmhVar = (zzdmh) this.l.zzb();
        ta2 ta2Var2 = g3.g;
        zzguoVarZzs2.f(new zzdje(zzdmhVar, ta2Var2));
        zzguoVarZzs2.f(new zzdje((yu2) this.u.zzb(), ta2Var2));
        return new pf2(zzcweVar, context, zzcjlVar, i, i31Var, zzdmcVar, new zzdiq(zzguoVarZzs2.h()), (zzdbs) this.v.zzb(), ((zzcdu) gd2Var.D.zzb()).c, (zzdxz) se3Var.zzb());
    }

    @Override // com.google.android.gms.internal.ads.zzcti
    public final zzdlr e() {
        return (zzdlr) this.x.zzb();
    }

    public final zzduu f() {
        return (zzduu) this.w.zzb();
    }
}
